figure;
hold on; grid on;
plot(0:0.1:(0.1*(371-1)), form_err_15, "green", "LineWidth", 1.5);
plot(0:0.1:(0.1*(202-1)), form_err_10, "blue", "LineWidth", 2);
plot(0:0.1:(0.1*(208-1)), form_err_6, "red", "LineWidth", 3);
%title("\textbf{Formation error comparison between different measurement noise simulations [m]}", "Interpreter","latex","FontSize", 14);
set(gca, "FontSize", 20);
xlim([0 20]);
xlabel("Time [s]", "Interpreter","latex","FontSize", 40);
ylabel("Formation error [m]", "Interpreter","latex","FontSize", 40);
legend("15cm", "10cm", "6cm", "Interpreter","latex","FontSize", 25);